// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVZpZfn0UyTgf-H2MtWeYwz13Ujfxk218',
    appId: '1:775556496613:web:73490838c94544b82f680c',
    messagingSenderId: '775556496613',
    projectId: 'notesapp-8ce04',
    authDomain: 'notesapp-8ce04.firebaseapp.com',
    storageBucket: 'notesapp-8ce04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUzghD-67IbuX-oEdxRplSqD90ZvM5HiY',
    appId: '1:775556496613:android:56ae361b61b59f8e2f680c',
    messagingSenderId: '775556496613',
    projectId: 'notesapp-8ce04',
    storageBucket: 'notesapp-8ce04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByB396ckccwFhVy4u4FWWRalJrOmcVhq0',
    appId: '1:775556496613:ios:603d1ff3a4c165ee2f680c',
    messagingSenderId: '775556496613',
    projectId: 'notesapp-8ce04',
    storageBucket: 'notesapp-8ce04.appspot.com',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByB396ckccwFhVy4u4FWWRalJrOmcVhq0',
    appId: '1:775556496613:ios:3037d17bd7d46e4c2f680c',
    messagingSenderId: '775556496613',
    projectId: 'notesapp-8ce04',
    storageBucket: 'notesapp-8ce04.appspot.com',
    iosBundleId: 'com.example.notesapp.RunnerTests',
  );
}
